### PR TITLE
Implemented more of the functionality

### PR DESCRIPTION
**Pull request by k0nserv**
I've implemented most of the setters and getters a side from the URL ones. I've also added tests and created a pod spec

### CODE REVIEW

**Comment by k0nserv** [comment]
Ping @zoul

**Comment by CodeReaper** [comment]
Had this been merged and podspec submitted to cocoapods.org already then I could have started using it...

**Comment by zoul** [comment]
Hah, sorry! Merging now.

**Comment by zoul** [comment]
The library should be available on CocoaPods in a few moments, please test and report if anything goes wrong. Sorry for the delay, happy hacking!

**Pull request merged**
